### ISSUE TITLE
Players speccing redie players.

### ISSUE THREAD

**Issue by breezboii** [chanz/redie#6] opened 2014-06-17 18:16 UTC
This is somewhat cool and somewhat not.

I think it mixes the alive with the dead a bit too much. And if redie players already can see other redie players it should maybe stay like that.

Atleast i dislike this option.
- .cfg

**Comment by chanz** [comment] 2014-08-12 17:21
Duplicate of #3 and will be handled by redie_hide_ghosts_from_observers.

Version: 2.12

**Closed as completed** 2014-08-12 19:00 UTC
Labels: enhancement
